import Head from "next/head";
import Header from "~/components/layout/Header";
import type { LayoutProps } from "~/types/LayoutProps";

export default function AdminLayout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <div className="px-6 pb-7 pt-2">{children}</div>
      </div>
    </>
  );
}
